[phases.setup]
nixpkgs = ['python38', 'python38Packages.pip']

[phases.install]
cmds = [
    'pip install --upgrade pip',
    'pip install -r requirements.txt'
]

[phases.build]
cmds = []

[start]
cmd = 'python -m streamlit run main_v2.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true --server.enableCORS=false --server.enableXsrfProtection=false'