name: draftshift
services:
- name: web
  build_command: pip install -r requirements.txt
  run_command: python run_server.py
  envs:
  - key: PYTHONUNBUFFERED
    value: "1"
  http_port: 8000
  health_check:
    http_path: /
