[phases.setup]
providers = ["python"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "python -m uvicorn fastapi_app:app --host 0.0.0.0 --port $PORT"