"""Word legal memo generator for CaseGrid medical analysis."""
from __future__ import annotations

from pathlib import Path
from typing import Any

from docx import Document

MEMO_OUTPUT_DIR = Path(__file__).resolve().parents[1] / "assets" / "memo_output"
MEMO_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


def generate_memo(
    patient_name: str,
    dob: str | None,
    record_range: str,
    evaluation: dict[str, Any],
    evidence: list[dict[str, Any]],
    missing: list[str],
) -> Path:
    """Create and save a legal memorandum in .docx format."""
    doc = Document()

    doc.add_heading("THE ROBINSON LAW FIRM, PROF. CORP.", level=0)
    doc.add_heading("CaseGrid Medical Record Analysis Memorandum", level=1)

    # Executive Summary
    doc.add_heading("Executive Summary", level=2)
    doc.add_paragraph(f"Patient: {patient_name}")
    doc.add_paragraph(f"Date of Birth: {dob or 'Unknown'}")
    doc.add_paragraph(f"Record Range: {record_range}")
    doc.add_paragraph(f"Qualification Status: {evaluation.get('status', 'Unknown')}")

    # Criteria Table
    doc.add_heading("Criteria Table", level=2)
    table = doc.add_table(rows=1, cols=5)
    headers = table.rows[0].cells
    headers[0].text = "Field"
    headers[1].text = "Operator"
    headers[2].text = "Expected"
    headers[3].text = "Extracted"
    headers[4].text = "Result"

    for item in evaluation.get("details", []):
        rule = item.get("rule", {})
        row = table.add_row().cells
        row[0].text = str(rule.get("field", ""))
        row[1].text = str(rule.get("operator", ""))
        row[2].text = str(rule.get("value", ""))
        row[3].text = str(item.get("value", ""))
        row[4].text = (
            "Pass" if item.get("result") is True else "Fail" if item.get("result") is False else "Insufficient"
        )

    # Detailed Findings
    doc.add_heading("Detailed Findings", level=2)
    doc.add_paragraph(
        "The following points summarize normalized medical indicators and extracted context from source documents."
    )
    for ev in evidence[:25]:
        doc.add_paragraph(
            f"Page {ev.get('page', '?')}: [{ev.get('normalized', 'evidence')}] {ev.get('text', '')}",
            style="List Bullet",
        )

    # Missing Data
    doc.add_heading("Missing Data", level=2)
    if missing:
        for item in missing:
            doc.add_paragraph(item, style="List Bullet")
    else:
        doc.add_paragraph("No missing required data identified.")

    # Recommendations
    doc.add_heading("Recommendations", level=2)
    if evaluation.get("status") == "Qualified":
        doc.add_paragraph("Proceed with litigation intake and downstream case development.")
    elif evaluation.get("status") == "Insufficient Data":
        doc.add_paragraph("Request additional records and confirm pathology/diagnosis documentation.")
    else:
        doc.add_paragraph("Review with attorney for discretionary qualification override if appropriate.")

    # Appendix
    doc.add_heading("Appendix", level=2)
    doc.add_paragraph("Generated by CaseGrid Medical Analyzer. This memo is a draft support document and not legal advice.")

    safe_name = "_".join((patient_name or "patient").split())
    output_path = MEMO_OUTPUT_DIR / f"{safe_name}_talc_memo.docx"
    doc.save(output_path)
    return output_path
